name: Run Cloudflare Gotty VM

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Switch to persistent branch
        run: |
          git fetch origin vm-data
          git checkout vm-data

      - name: Restore data
        run: |
          mkdir -p .vm_data
          cp -r /vm_data/* .vm_data 2>/dev/null || true

      - name: Make start.sh executable
        run: chmod +x start.sh

      - name: Start VM
        run: ./start.sh

      - name: Save VM data after job completes
        if: always()
        run: |
          rm -rf .vm_data
          cp -r /vm_data .vm_data || true
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .vm_data
          git commit -m "🔄 Save VM data" || echo "No changes to commit"
          git push origin vm-data
